### ISSUE TITLE
Make a AppIcon

### ISSUE THREAD

**Issue by zengxs** [ehaut/EhautX#1]
We need an app icon.

**Comment by CHN-STUDENT** [comment]
Try to use the old vesion of appicon.
https://raw.githubusercontent.com/CHN-STUDENT/srun3k-client-ui/master/srun-3k-ui/myapp.ico

**Comment by zengxs** [comment]
@CHN-STUDENT Leet me take a look.

**Comment by noisky** [comment]
我感觉新版的图标比较好看
特别是蜗牛的那个小眼神 简直神来之笔
[https://raw.githubusercontent.com/CHN-STUDENT/srun3k-client-ui/master/srun-3k-ui/new.ico](https://raw.githubusercontent.com/CHN-STUDENT/srun3k-client-ui/master/srun-3k-ui/new.ico)

**Comment by zengxs** [comment]
@noisky Ok, agree with you. Can you provide an original design file for me, such as `PSD` file?

And we need more artworks.

**Comment by CHN-STUDENT** [comment]
@zengxs  Can not find its source file. We can only find its `PNG` file. Please try to use it.
![new](https://user-images.githubusercontent.com/21209416/50394415-496fd500-0798-11e9-98d2-bcfd61889796.png)

**Comment by zengxs** [comment]
@CHN-STUDENT Ok, thanks.
